# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalTracker', '0002_auto_20161108_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
