# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalTracker', '0003_goal_current_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='amount',
            new_name='goal_amount',
        ),
        migrations.AlterField(
            model_name='goal',
            name='current_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
