# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundTracker', '0002_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='owner',
        ),
        migrations.AddField(
            model_name='transaction',
            name='fund',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fundTracker.Fund'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fund',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
